CREATE TABLE procurador(
DNI SERIAL PRIMARY KEY,
NOMBRE VARCHAR(100),
APELLIDO VARCHAR(100),
DIRECCION VARCHAR(100)
);

CREATE TABLE cliente(
DNI SERIAL PRIMARY KEY,
NOMBRE VARCHAR(255),
APELLIDO VARCHAR(255),
DIRECCION VARCHAR(255)
);

CREATE TABLE Asuntos(
Numero_Expediente SERIAL PRIMARY KEY NOT NULL,
f_inicio DATE,
f_fin DATE,
periodo INTEGER,
estado BOOLEAN,
tramite BOOLEAN, 
archivado BOOLEAN, 
id_cliente INTEGER REFERENCES cliente(DNI),
id_procurador INTEGER REFERENCES procurador(DNI)
);

